#!/bin/bash
#
# reserve 1 cores and 8 GB of memory on 1 host
#
#BSUB -n 1
#BSUB -R "rusage[mem=5000]"
#BSUB -R "span[hosts=1]"
#
#BSUB -u floris.drijver@tno.nl

#BSUB -J ns3_3
#
NS_LOG=CoapClientApplication:CoapServerApplication:Application:wsn-iot-v1  ../static_exe.run  --ndn=0 --pcap=0 --simtime=1000 --periph=25 --head=30 --con_inside=2 --con_leaf=2 --freshness=300 --zm_q=0 --zm_s=0.64 --min_freq=0.0167 --max_freq=0.0083 --cache=590 --payloadsize=14 --ipbackhaul=1 --csma_delay=25 --rng=2203 &> RUN3.txt
